### PR TITLE
remove page contents container

### PR DESCRIPTION
**Pull request by gavtaylor**
fyi @garryprior

### CODE REVIEW

**Comment by garryprior** [comment]
thanks @gavtaylor .  I don't have permission to merge PRs on this repo, only on the main docs.ukfast one.  I guess @laf will need to merge it.

**Comment by gavtaylor** [comment]
@laf any chance you could give @garryprior power to merge this in?

**Comment by garryprior** [comment]
@laf @gavtaylor not sure this worked - I can still see the page contents box on docs.ukfast pages (have tested several).

image

**Comment by zyio** [comment]
A rebuild of the [main project](https://github.com/ukfast/docs.ukfast.co.uk) in travis should drag in the new changes

**Comment by garryprior** [comment]
thanks @zyio 

no idea how to do that - another one for @laf ?

**Comment by zyio** [comment]
Think you might be able to do it @garryprior, if you head to https://travis-ci.org/ukfast/docs.ukfast.co.uk/builds/233592368 and sign in with github, there should be a  'retry' or 'rerun' or similar.

**Comment by garryprior** [comment]
Restart Job?

image

**Comment by zyio** [comment]
Looks about right. The same could be achieved by pushing something new to master, but if you've got nothing ready, this should be fine

**Comment by gavtaylor** [comment]
@garryprior did you try clicking restart job?

**Pull request merged**
